CREATE TABLE 
	CLIENTES (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,  
		NOME VARCHAR(100) NOT NULL,
		CPF  VARCHAR(14) NOT NULL UNIQUE        
	);

CREATE TABLE 
	CARROS (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		MODELO VARCHAR(50) NOT NULL,
		ANO_LANCAMENTO INTEGER NOT NULL
	);

CREATE TABLE 
	VENDAS (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		CLIENTE_ID INTEGER NOT NULL,
		CARRO_ID INTEGER NOT NULL,
		DATA_VENDA DATE NOT NULL,
		FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
		FOREIGN KEY (CARRO_ID) REFERENCES CARROS(ID)
	);