SELECT
    VE.CLIENTE_ID,
    CL.NOME,
    COUNT(*) AS TOTAL_VENDAS_UNO
FROM 
	VENDAS VE
INNER JOIN 
	CARROS CA ON VE.CARRO_ID = CA.ID
INNER JOIN 
	CLIENTES CL ON CL.ID = VE.CLIENTE_ID
WHERE 
	CA.MODELO = 'Uno'
GROUP BY 
	VE.CLIENTE_ID, CL.NOME
ORDER BY 
	TOTAL_VENDAS_UNO DESC;