WITH ELEGIVEIS AS (
    SELECT
        CL.ID,
        CL.NOME,
        CL.CPF,
        MIN(VE.DATA_VENDA) AS DATA_PRIMEIRA_VENDA
    FROM 
		CLIENTES CL
    INNER JOIN 
		VENDAS VE ON CL.ID = VE.CLIENTE_ID
    INNER JOIN 
		CARROS CA ON VE.CARRO_ID = CA.ID
    WHERE 
		CL.CPF LIKE '0%' AND CA.ANO_LANCAMENTO = 2021 AND NOT EXISTS (
			SELECT 
				1
			FROM 
				VENDAS VE2
			INNER JOIN 
				CARROS CA2 ON VE2.CARRO_ID = CA2.ID
			WHERE 
				VE2.CLIENTE_ID = CL.ID AND CA2.MODELO = 'Marea'
			GROUP BY 
				VE2.CLIENTE_ID
			HAVING 
				COUNT(*) >= 2
      )
    GROUP BY 
		CL.ID, CL.NOME, CL.CPF
)
SELECT 
	ID, NOME, CPF
FROM 
	ELEGIVEIS
ORDER BY 
	DATA_PRIMEIRA_VENDA
LIMIT 
	15; 