WITH SORTEADOS AS (
    SELECT 
		CL.ID
    FROM 
		CLIENTES CL
    INNER JOIN 
		VENDAS VE ON CL.ID = VE.CLIENTE_ID
    INNER JOIN 
		CARROS CA ON VE.CARRO_ID = CA.ID
    WHERE 
		CL.CPF LIKE '0%' AND CA.ANO_LANCAMENTO = 2021 AND NOT EXISTS (
			SELECT 
				1
			FROM 
				VENDAS VE2
			INNER JOIN 
				CARROS CA2 ON VE2.CARRO_ID = CA2.ID
			WHERE 
				VE2.CLIENTE_ID = CL.ID AND CA2.MODELO = 'Marea'
			GROUP BY 
				VE2.CLIENTE_ID
			HAVING COUNT(*) >= 2
		)
    GROUP BY 
		CL.ID
    ORDER BY 
		MIN(VE.DATA_VENDA)
    LIMIT 
		15
)
DELETE FROM VENDAS
WHERE NOT EXISTS (
	SELECT 
		1 
	FROM 
		SORTEADOS SO 
	WHERE 
		SO.ID = VENDAS.CLIENTE_ID
);